on:
  workflow_call:
  push:
    paths:
      - backend/**
  workflow_dispatch:
  
jobs:
  unit_tests:
    uses: ./.github/workflows/unit_tests.yml

  build_app:
    runs-on: ubuntu-latest
    needs: 
      - unit_tests
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
    
      - name: npm install and build backend
        run: |
          cd ./backend
          npm install
          npm audit fix
          npm run build --if-present
          npm run test --if-present
    
      - name: Audit backend
        run: |
          cd ./backend
          npm audit | grep -E "high|critical" && echo "Vulnerabilities found" || echo "No vulnerabilities found"
    
      - name: Run esLint on backend
        run: |
          cd ./backend
          npm run lint