on: [push]
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install backend dependencies
        run: |
          cd ./backend
          npm install

      - name: Start backend
        run: |
          cd ./backend
          npm start &
      
      - name: Install frontend dependencies
        run: |
          cd ./frontend
          npm install
      
      - name: Build the app
        run: npm run build  
        working-directory: frontend

      - name: Start the app
        run: npm start &
        working-directory: frontend

      - name: Cypress run on Edge
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          browser: edge
      
      - name: Cypress run on Chrome
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          browser: chrome

      - name: Cypress run on Firefox
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          browser: firefox