on: [push]
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install backend dependencies
        run: |
          cd ./backend
          npm start
          sleep 5
      
      - name: Install frontend dependencies
        run: |
          cd ./frontend
          npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          build: npm run build
          start: npm start