on: [push]
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@v4

      - name: Start frontend
        run: |
          ./frontend
          npm run dev
      
      - name: Start backend
        run: |
          ./backend
          npm start

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          build: npm run build
          start: npm start