on:
  workflow_call:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master 
        with:
          release_branch: test-semver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
