on:
  workflow_call:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: SemRelease
        uses: btnguyen2k/action-semrelease@v3.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
