on:
  push:
    branches: 
      - "test-workflow"
    tags:
      - "v*.*.*"
    #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') ##TODO check the format is X.Y.Z and they are number
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm audit fix
        npm run build --if-present
        npm run test --if-present

    - name: Audit
      run: ping -i 1 127.0.0.1 #TODO

    - name: Linting
      run: ping -i 1 127.0.0.1 #TODO

    - name: Unit Testing
      run: ping -i 1 127.0.0.1 #TODO

    - name: Deploy on Docker Hub
      run: ping -i 1 127.0.0.1 #TODO
