on:
  push:
    branches: 
      - "test-workflow"
    tags:
      - "v*.*.*"
    #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') ##TODO check the format is X.Y.Z and they are number
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: npm install, build, and test backend #TODO if the user put "backend" in the commit description only?
      run: |
        cd ./backend
        npm install
        npm audit fix
        npm run build --if-present
        npm run test --if-present

    - name: npm install, build, and test frontend #TODO if the user put backend in the commit description only? TODO async?
      run: |
        cd ./frontend
        npm install
        npm audit fix
        npm run build --if-present
        npm run test --if-present

    - name: Build and push Docker image #https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

    #- name: Audit
    #  run: ping -n 1 127.0.0.1 #TODO

    #- name: Linting
    #  run: ping -n 1 127.0.0.1 #TODO

    #- name: Unit Testing
    #  run: ping -n 1 127.0.0.1 #TODO 

    #- name: Build the docker image
    #  run: docker build . --file Dockerfile --tag todo-app:$(date +%s)